name: Turnaround-Check-Action
on:
  workflow_dispatch:
  schedule:
    - cron: '35 7 * * *' # 日本時間 16:35に実行

jobs:
  run-turnaround:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests pandas yfinance
      
      - name: Run script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python main.py
